
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://shubhamdeshpande.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: 

# Google tracking id

google-tracking-id: "UA-128535964-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Shubham Deshpande"
title: "Shubham Deshpande"
description: "Personal website of Shubham Deshpande."
keywords: "shubham, deshpande, personal, jekyll, theme"
favicon: "/img/favicon.png"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/timeline/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 500
delete-speed: -20
delete-delay: 2000
lines:
# Me
  - text: "Welcome to the best Shubham Deshpande site on the internet."
  
# Protips
  - text: "Protip:^500 Always get Piri masala with fries.^500<br />Way better than ketchup."

# Hope
  - text: "One day, I'm going to fly to the moon.^500<br />I just need to wait until I have an extra five million dollars,^500<br />and for the technology to be reinvented and mass marketed.^500<br />So like next year, maybe the year after?"

# Bad Jokes
  - text: "These things load in a random order.^500<br />But once you see the same one twice it means they're repeating.^500<br />You can stop after that."

me-img: "/img/mypic.jpg"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: False
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False

disqus-shortname: "shubham"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/sppu.jpg"
    date: "2015 - 2018"
    description: "Final Year Student Smt. Kashibai Navale College of Engineering (Bachelor of Engineering in Computer Engineering)
                  <br/>Grade: First Class with Distinction
                  <br/>GPA: 9.05/10"
  
  - image: "/img/timeline/khs.png"
    date: "2013 - 2015"
    description: "Junior College bifocal(Computer Science) (12th Grade)"

  - image: "/img/timeline/sinhgad.jpg"
    date: "2001 - 2013"
    description: "Primary, Secondary, and High School (10th Grade)"  

# First image of the Timeline

timeline-img: "/img/mypic.jpg"

###########
# Contact #
###########

email: "shubhamdeshpande123@gmail.com"
phone: "8390278664"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Shubham Deshpande"
author_blurb_image: "/img/mypic.jpg"

##################
# Social Buttons #
##################
social:
  - title: "facebook"
    url: "https://www.facebook.com/beingshubhamdeshpande"
  - title: "github"
    url: "https://github.com/shubhamdeshpande"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/shubham-deshpande-0aa790147/"
  - title: "twitter"
    url: "https://twitter.com/deshpa_shubham"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Timeline: 'timeline'
  Blog: 'latest-post'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
